### ISSUE TITLE
Ability to add AWS certificate ID in configuration file

### ISSUE THREAD

**Issue by snario** [convox/rack#1034]
It would be convenient to have this ability:

```yml
nginx:
    image: nginx
    ports:
        - 443:443
    labels:
        - convox.port.443.protocol=https
        - convox.port.443.cert=acm-blahblah
```
