### ISSUE TITLE
convox.start.shift also shifts deploys + wrong increment

### ISSUE THREAD

**Issue by frsechet** [convox/rack#1078]
The following docker-compose file results in the wrong settings in the running app:
```
main:
  build: .
  labels:
    - convox.port.80.protocol=http
    - convox.port.443.protocol=https
    - convox.start.shift=1000
  ports:
    - 80:80
    - 443:80
```
result after `convox deploy`:
```
$ convox apps info
Name       danis-trends
Status     running
Release    REVSFIIGSRE
Processes  main
Endpoints  xxxxx.eu-west-1.elb.amazonaws.com:2443 (main)
           xxxxx.eu-west-1.elb.amazonaws.com:2080 (main)
```

- The shift should not happen in convox deploy,
- The shift should not be by 2000 but 1000 only.
