### ISSUE TITLE
App-level shared EFS volumes

### ISSUE THREAD

**Issue by snario** [convox/rack#1140]
Right now you can't have a config like this with a shared filesystem:

``` yml
    thing:
        volumes:
            - /efs

    other-thing:
        volumes:
            - /efs
```

They don't actually have the same file system.

I can't think of a case where you would not want this behaviour, however, and I think it is just about setting the name of the EFS to be the same?

**Comment by jayjanssen** [comment]
+1, though I think this brings up another potential problem.  If all volumes are app-level, then it is possible to have naming conflicts between containers where you **don't** want to share a volume -- imagine a /data on multiple containers, you may want to be able to specify which is which.

A start of an idea:

```
services:
  redis:
    image: convox/redis
    ports: 
      - 6379
    volumes:
      - /data
  other-service1:
    labels:
     - convox.volumes.shared.global=true
    volumes:
      - /shared:/data
  other-service2:
    labels:
     - convox.volumes.shared.global=true
    volumes:
      - /shared:/whatever
```

In this case: other-service1:/data and other-service2:/whatever are the same EFS, but /data on redis localized to only redis containers.
