### ISSUE TITLE
External docker repository

### ISSUE THREAD

**Issue by bobzoller** [convox/rack#1244]
As part of our CI flow, we build docker containers and push them to a private docker registry.  All of our apps then create an empty directory with _only_ a docker-compose.yml file in it and run `convox deploy`, eg:

```yaml
foo:
  image: goodeggs/foo:abcdefg
  command: runit
```

Convox (as part of the build process) then copies those docker images into the ECR for each application.  ECS Tasks then reference those ECR images.

---

We'd like to be able to opt out of ECR, reference our external registry directly, and in return recover a bunch of time spent pushing and pulling docker images around the internets during the deploy process.

Thoughts / reactions / guidance?  As always, I'm happy to start working on a PR.

**Comment by bobzoller** [comment]
You know there's another complexity here I failed to explain.  Many of our apps run a web process and several background workers that we'd like to scale independently.  An example docker-compose.yml for app `myapp` at git sha `abcdefg`might be:

```yaml
web:
  image: goodeggs/myapp:abcdefg
  command: npm run web
  environment:
    - PORT=3000

ordereventworker:
  image: goodeggs/foo:abcdefg
  command: npm run event_worker orders

deliveryeventworker:
  image: goodeggs/myapp:abcdefg
  command: npm run event_worker deliveries
```

The problem I described above is exacerbated by this, as Convox has to do a push/pull for each process, where in reality these are all the same image.
