### ISSUE TITLE
Error using dockerfile in v1 docker-compose.yml

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#1258]
Create these 2 files:

**Dockerfile.test**
```
FROM httpd
```
**docker-compose.yml**
```
web:
  build: .
  dockerfile: Dockerfile.test
  ports:
    - 80:80
```

If you deploy this app, you'll get the following error on release promotion: `ERROR: dockerfile specified twice for web`

If you change `docker-compose.yml` to a V2 format, the error goes away:

```
version: 2
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - 80:80
```
