### ISSUE TITLE
Getting invalid manifest errors when specifying env variables for image-based process

### ISSUE THREAD

**Issue by crohr** [convox/rack#128]
In `docker-compose.yml`:

```
postgres:                                                                             
  image: postgres:9.4                                                                 
  environment:                                                                        
    POSTGRES_USER: postgres                                                           
    POSTGRES_PASSWORD: postgres                                                       
```

Then:
```
convox deploy
...
Promoting RPUWSXDYKYE... ERROR: invalid manifest: yaml: unmarshal errors:
  line 13: cannot unmarshal !!map into []string
```

Removing the `environment` section from the `docker-compose.yml` file makes the deployment succeed. Is that the expected behaviour?
