### ISSUE TITLE
suggest running `convox doctor` when `convox start` fails

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#1321]

**Comment by ianmalott** [comment]
As an example, a common problem is forgetting to add required environment variables to the .env file. Right now `convox start` just fails silently. Below, the `REQUIRED` env var is not set in .env.

docker-compose.yml
```
version: '2'
services:
  web:
    build: .
    environment:
      - FOO
      - REQUIRED
...
```

.env
```
FOO
```

```
$ convox start

$
```
