### ISSUE TITLE
allow empty defaults for environment vars in docker-compose.yml

### ISSUE THREAD

**Issue by bisrael** [convox/rack#1338]
There appears to be no way to set a blank default for environment variables in `docker-compose.yml`:

``` yaml
version: "2"
services:
  web:
    environemnt:
    - VAR_1=
    - VAR_2=""
```

`convox start|doctor` will complain that `VAR_1` is missing, but set `VAR_2` not to an empty string as one might imagine, but to a string literally containing two quotation marks (i.e.: `"\"\""`)

i can see two resolutions:
1. Accept `VAR_1=` form to mean blank string
2. Disallow `VAR_1=` form, accept `VAR_2=""` as empty string by dropping the quotes

No. 2 seems more able to handle edge cases including variables whose defaults may contain desired trailing spacing (e.g.: `VAR_3="      "` becomes acceptable to cover that case)

Thanks!
