### ISSUE TITLE
Cannot link service that is linked to another service

### ISSUE THREAD

**Issue by lukevella** [convox/rack#1368]
In my project I have 3 services, an api, client and database. The client is linked to the API and the API is linked to database. This linking causes both `convox doctor` and `convox start` to crash with no error. Here is my `docker-compose.yml`

```yml
version: "2"
services:
  client:
    build: ./client
    command: ["node", "."]
    ports:
      - 8080:8080
    environment:
      - API_URL
    links:
      - api
  api:
    build: ./api
    command: ["node", "."]
    ports:
      - 3000:3000
    environment:
      - DB_URL
    links:
      - db
  db:
    image: convox/mongo
    ports:
      - 27017
```

[I made a repository to demonstrate this issue.](https://github.com/lukevella/convox-links-issue)
