### ISSUE TITLE
Variable Substitution not working in docker-compose `command`

### ISSUE THREAD

**Issue by losttime** [convox/rack#1376]
I'm trying to utilize docker-compose variable substitution, but it doesn't seem to be working. Is `docker-compose.yml`s `command` option parsed differently than other options?

- I've got the variable defined in the ENV tab of my convox app.
- The variable shows up when I run `convox env --app my-app`
- When I run `convox deploy --app my-app` the container fails to run (the args I'm passing in with `command` are required args)
- If I hard code the value into `docker-compose.yml`, the container starts up fine.

Here's a sample of what my docker-compose is like
```
version: '2'
services:
  logger:
    image: logzio/logzio-docker
    privileged: true
    restart: always
    command: [-t, $LOGZIO_TOKEN]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

If I do `convox start` I see that the variable is substituted in the local run command, but I don't have the same visibility into what's happening in AWS. Based on the logs after the build is finished, it looks like the token is not being provided correctly, leading me to believe the variable substitution is not happening as I'd expect.

**Comment by losttime** [comment]
Let me know if there's anything I can do to provide additional detail.

**Comment by soulware** [comment]
Looks like we just saw the same issue.
We have tried the following, all with the same issue - 

```
command: [/usr/local/bin/foo, "--baz", $FOO]
command: [/usr/local/bin/foo, "--baz", "$FOO"]
command: [/usr/local/bin/foo, "--baz", "${FOO}"]
```

I believe the following attempt fails to parse as valid yaml during the build process - 

```
command: [/usr/local/bin/foo, "--baz", ${FOO}]
```

**Comment by mattmanning** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Variable substitution not working in `command` in docker-compose.yml](https://trello.com/c/M2iZR7Dl/1121-variable-substitution-not-working-in-command-in-docker-compose-yml)

**Comment by awsmsrc** [comment]
Just an update here, so the parsing works. 
The trouble is you are trying to use an env variable from the runtime of your app. 
This is not present in the environment of the rack 

a double $ sign ignores interpolation, this means if your command is set up correctly you can have the command interpolate the variable at run time.

The following worked for me

```
version: "2"
services:
  one:
    image: "ubuntu"
    environment:
      - WORD=FOO
    command: "echo $$WORD"
```

This leaves the following questions open @ddollar @miguel 

1) should the build process know about the app env?
2) Should we have a build env?
3) Is the above good enough
