### ISSUE TITLE
Missing / in *_URL env var generated by docker-compose.yml linking

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#1446]
**To reproduce:**

Create a new app and deploy this `docker-compose.yml` to it:

```
web:
  image: httpd
  ports:
    - 80:80
  links:
    - database
database:
  image: postgres:9.6.1
  environment:
    - LINK_USERNAME=postgres
    - LINK_PASSWORD=password
    - LINK_PATH=postgres
    - LINK_SCHEME=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
  ports:
    - 5432
```

When the app boots, `convox exec <id> bash` onto the `web` container and run `echo $DATABASE_URL`

**Expected result:**
`postgres://postgres:password@<hostname>:5432/postgres`

**Actual result:**
`postgres://postgres:password@<hostname>:5432postgres`
(There is a missing / between the port and the path).
