### ISSUE TITLE
Handle null environment variables in map format

### ISSUE THREAD

**Issue by idris** [convox/rack#1471]
A continuation of #112 and #578...

It seems leaving environment variables null when using the map format doesn't work.

When I run this `docker-compose.yml` file through `convox doctor`, it says the file is not valid yaml:
```yaml
version: '2'
services:
  web:
    build:
      context: .
    command: bin/www
    environment:
      NODE_ENV:
      PORT: 3000
    ports:
      - 80:3000
```

YAML has (at least) two ways to specify null values:
```yaml
environment:
  KEY_NAME:
```
```yaml
environment:
  ? KEY_NAME
```
