### ISSUE TITLE
ECS Task Placement Policies

### ISSUE THREAD

**Issue by spencerhakim** [convox/rack#1504]
[tl;dr - granular control over how tasks are placed onto clusters](https://aws.amazon.com/blogs/compute/introducing-amazon-ecs-task-placement-policies/)

No ideas or opinions on how Convox should handle this feature, or if it even should, but I'm dropping it here for discussion/tracking. Happy new year! 🎉

**Comment by mwarkentin** [comment]
The biggest use case for us that comes to mind would be around potentially splitting out where certain types of processes run - potentially dedicating some boxes specifically for our worker tasks so that we can prevent any chance of processes there from causing performance issues for our user-facing processes.

We also find that our tasks "cluster" on a couple of boxes, and usually have 1-2 instances that are quite under-utilized. Perhaps the new scheduling features could help keep things more balances across the cluster.

**Comment by mwarkentin** [comment]
It looks like Amazon has added two new settings for ECS tasks: 

* I've been unable to find any documentation about configuring task placement with Cloudformation, and no mention on [Cloudformation release history](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html) - this may not be supported yet.
* Both [constraints](http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_CreateService.html#ECS-CreateService-request-placementConstraints) and [strategies](http://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_CreateService.html#ECS-CreateService-request-placementStrategy) work with ECS services
* Multiple constraints and strategies can be used
* [Placement Strategies](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-placement-strategies.html)
  * Current limit is 5 strategies
  * Currently 3 strategy types: `binpack`, `spread`, and `random`
  * `binpack` and `spread` also take a `field` argument
* [Placement Constraints](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-placement-constraints.html)
  * Current limit is 10 constraints
  * Currently 2 constraint types: `distinctInstance` and `memberOf`
  * Both constraints take an `expression` argument which uses the [ECS Cluster Query Language](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/cluster-query-language.html)

**Comment by nzoschke** [comment]
Definitely want to use the spread strategy for daemons instead of the implementation on 1503.

Proposal to turn on spread is a `convox.daemon` label.

```
version: '2'
services:
  agent:
    image: datadog/docker-dd-agent:latest
    environment:
     - API_KEY
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc
      - /cgroup/:/host/sys/fs/cgroup
    privileged: true
    labels:
      - convox.daemon=true
```
