### ISSUE TITLE
Support substituting environment variables in docker-compose file

### ISSUE THREAD

**Issue by amsb** [convox/rack#1607]
Docker Compose supports substituting environment variables in Compose files:

* [Substituting environment variables in compose files](https://docs.docker.com/compose/environment-variables/#/substituting-environment-variables-in-compose-files)
* [Variable substitution](https://docs.docker.com/compose/compose-file/#variable-substitution)

Supporting this in Convox would provide a convenient tactic for maintaining parity between various environments. For example, the following `docker-compose.yml` file:

```yaml
version: '2'

services:
  web:
    build: .
    command: serve.py
    ports:
      - 80:80
    links:
      - postgres
    environment:
      - POSTGRES_URL="postgres://${PGUSER}:${PGPASSWORD}/${PGDATABASE}"

  postgres:
    image: convox/postgres
    ports:
      - 5432
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DATABASE=${PGDATABASE}
      - LINK_USERNAME=${PGUSER}
      - LINK_PASSWORD=${PGPASSWORD}
      - LINK_PATH="/${PGDATABASE}"
```

along with this `.env` file:

```
PGUSER=TESTUSER
PGPASSWORD=TESTPASS
PGDATABASE=myapp
```

would have the following advantages:

1. Set postgres user, password, and database only once, in `.env`.
2. Better control accidentally leaking insecure credentials to production.
3. Use same files for both Docker Compose and Convox.

In this particular example, there is the disadvantage that deployment would require explicitly setting environment values for a service that would be replaced by a resource and scaled to 0.

The 2.1 Docker Compose file format also supports `${VARIABLE:-default}` and `${VARIABLE-default}` inline default value syntax.
