### ISSUE TITLE
validate cron jobs

### ISSUE THREAD

**Issue by contra** [convox/rack#1942]
On deploy, you can get bit with this error: `Parameter ScheduleExpression is not valid.` causing everything to fail and roll back. This is with a normal looking cron such as:

```yaml
version: '2'
services:
  web:
    build: .
    command: node /usr/src/app/bin/server
    labels:
      - convox.cron.import-all=0 2 * * ? "some command"
      - convox.cron.import-waze=*/2 * * * * ? "some command"
      - convox.cron.import-scf=*/6 * * * * ? "some command"
```

`convox doctor` reports no issues and neither does `deploy` until it blows up and fails.
