### ISSUE TITLE
ability to create lambda functions

### ISSUE THREAD

**Issue by contra** [convox/rack#2030]
API can go a number of ways here, opening this for discussion (matt told me to).

Our use case is creating a few functions that can be invoked by our API on demand.

A couple of them are:
- Sending email
- Scheduling stuff
- Running user-submitted code in a sandbox

Would be looking at expanding that as needed, but fundamentally the architecture is still one main API that calls these functions, nothing fancy that people are doing with serverless.

This API would work for our needs:

```yaml
version: '2'
services:
  web:
    build: .
    command: node /usr/src/app/bin/server
    labels:
      - convox.cron.run-import-jobs=* * * * ? npm run import
      - convox.functions.schedule-import=functions/schedule-import
      - convox.functions.send-email=functions/send-email
    environment:
      - PORT=3000
      - NODE_ENV
    ports:
      - 80:3000
      - 443:3000
    volumes:
      - .:/usr/src/app
```

Format for the label is basically `convox.functions.<fn name>=<folder path>` - the folder would have everything needed for the lambda function, and maybe a manifest could be used to track other stuff.

Other option (rough sketch):

```yaml
version: '2'
services:
  schedule-import:
    type: function
    // anything else needed for this
  web:
    type: server
    build: .
    command: node /usr/src/app/bin/server
    labels:
      - convox.cron.run-import-jobs=* * * * ? npm run import
    environment:
      - PORT=3000
      - NODE_ENV
    ports:
      - 80:3000
      - 443:3000
    volumes:
      - .:/usr/src/app
```

Adds a type param to services, `function` types get deployed as lambda functions - default is `server` (current way things work).
