### ISSUE TITLE
specifying scale to `convox start`

### ISSUE THREAD

**Issue by contra** [convox/rack#2106]
I have a service like this:

```yml
importer:
    build: ./services/importer
    environment:
      - NODE_ENV
    volumes:
      - /code
```

I don't want any of these running on their own - I trigger these manually with either a cron job or programmatically via the convox API. In production, I can scale this to -1 to solve the problem. Locally, it doesn't seem like there is any way to do this.

BTW - docker compose v3 has deployment fields that can specify counts and sizes, so maybe this would be a good use case for that.
