### ISSUE TITLE
load balancer path priority?

### ISSUE THREAD

**Issue by contra** [convox/rack#2128]
How does this work right now? https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-update-rules.html

Should a new label be added to adjust the priority of the current label `convox.router.path` ?

Given something like this:

```yaml
web:
  labels:
    - convox.router.path=/*
api:
  labels:
    - convox.router.path=/api/*
```

the web service will receive requests for `/api/test`, with no way to configure it.
