### ISSUE TITLE
Container build/tag order

### ISSUE THREAD

**Issue by benjamin0** [convox/rack#223]
It looks like containers aren't tagged until after they are all built. If a container's Dockerfile has a `FROM` statement that references one of the other containers (that hasn't been tagged yet) the build will fail. Perhaps each container should be tagged immediately after it is built?

**Comment by nzoschke** [comment]
Thank you for your input. Tagging after build is a straightforward change. Can you provide an example app that demonstrates the problem?

**Comment by benjamin0** [comment]
In our case we have a few Dockerfiles which all use the same custom base image. Once there's integration with ECR I think we could build and push that image separately, but we tried building it in the docker-compose file then referencing it in the individual dockerfiles in the `FROM` statement. This didn't work because the image wasn't tagged before the other containers were trying to reference it.

**Comment by nzoschke** [comment]
ECR integration just landed, see the private repos docs. Still this is a good idea and I hope to address it soon

**Comment by nzoschke** [comment]
Thanks for your patience on this, I'm learning a lot about what "soon" means.

Is this still a valid concern? I could still use a concrete docker-compose.yml file that you'd expect to work.

Something like this?

```
base:
  build: .
  dockerfile: Dockerfile
web:
  image: myapp/base
  ports:
    - 3000:3000
  volumes:
    - .:/usr/src/app
web2:
  image: myapp/base
  ports:
    - 3001:3001
  volumes:
    - .:/usr/src/app
```
