### ISSUE TITLE
[GEN2] convox.yml should support Dockerfile with another name

### ISSUE THREAD

**Issue by idris** [convox/rack#2380]
In Gen 1 we could do:
```yml
    build:
      context: .
      dockerfile: Dockerfile.web
```

In Gen 2, that doesn't work.  The build fails with the following message:
```
ERROR: open /tmp/290641930/Dockerfile: no such file or directory
```
