### ISSUE TITLE
[GEN2] Unable to use list syntax for commands

### ISSUE THREAD

**Issue by mwisner** [convox/rack#2398]
In docker-compose.yml files we are able to define complex commands in a list syntax.

```yml
services:
  kong:
    build:
      context: compose/kong/
      dockerfile: "Dockerfile"
    command: ["kong", "start", "--nginx-conf", "/etc/kong/custom_nginx.template", "--vv"]
```

Which was valid and supported in convox gen 1.

However in convox.yml:

```yml
services:
  kong:
    build: compose/kong/
    command: ["kong", "start", "--nginx-conf", "/etc/kong/custom_nginx.template", "--vv"]
    domain: ${API_HOST}
    port: 8000
```
Results in an error:
```
ERROR: yaml: unmarshal errors:
  line 3: cannot unmarshal !!seq into string
```

https://docs.docker.com/compose/compose-file/#command
