### ISSUE TITLE
[GEN 2] nginx and multiple ports in convox.yml

### ISSUE THREAD

**Issue by amlwwalker** [convox/rack#2450]
Hi,
Porting a gen 1 app to gen 2, I have created the following convox.yml
```
services:
  accounting:
    build: .
    domain: ${HOSTNAME}
    port: 3001
    health: /health
    environment:
      - HOSTNAME
      - ENVIRONMENT
      - MONGODB_DB
      - MONGODB_HOST
```

however in the Dockerfile, I am configuring nginx so that if a connection comes in over http, nginx redirects the user to https, which in turn forwards the connection to an app running on port 3001.

If I set the `port: 3001` to 80, or 443, I get a 503 error. I would also need it to be able to take connections on both of them. In docker-compose.yml, `ports:` was an array which worked nicely.

Whats the solution here? My domain provider doesn't allow for forwarding subdomains and I cant move the dns to another provider (long story...)

I haven't found any detail about generation 2 and ports, and would love some help!
