### ISSUE TITLE
[GEN2] Fail to update Service Name when have Domain set, due to priority conflict

### ISSUE THREAD

**Issue by ffjia** [convox/rack#2476]
For example, if I need to rename `nginx` to `nginx2`, CFN update will fail, since the ALB Listener Rule Priority is the same.
```
services:
  nginx:
    domain:
      - nginx.domain.tld
```

```
services:
  nginx2:
    domain:
      - nginx.domain.tld
```
