### ISSUE TITLE
crash on "convox start" - panic: runtime error: index out of range

### ISSUE THREAD

**Issue by ndbroadbent** [convox/rack#2508]
```
$ uname -v
Darwin Kernel Version 16.7.0: Thu Jan 11 22:59:40 PST 2018; root:xnu-3789.73.8~1/RELEASE_X86_64

$ convox -v
client: 20180226234518
server: 20180227221242 (console.convox.com)

$  docker -v
Docker version 17.12.0-ce, build c97c6d6
```

### Output from `convox start`

```
...
build  │ Successfully built cd7aded298fe
build  │ Successfully tagged my_app/web:latest
web    │ running: docker run -i --rm --name my_app-web -e LANG=en_US.UTF-8 -e PORT=4001 -e RAILS_LOG_TO_STDOUT=enabled -e RAILS_SERVE_STATIC_FILES=enabled --privileged -p 0:4001/tcp -p 0:4001/tcp --cpu-shares 512 --memory 1073741824 my_app/web
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/convox/rack/manifest1.(*Service).SyncPaths(0xc420211198, 0xc42044e160, 0xc42007ef00, 0xc42044e101)
	/tmp/release.ZeQoT/src/github.com/convox/rack/manifest1/service.go:215 +0xb06
github.com/convox/rack/manifest1.(*Run).Start(0xc4200c61c0, 0x0, 0xc4202e2f30)
	/tmp/release.ZeQoT/src/github.com/convox/rack/manifest1/run.go:165 +0x1c30
main.startGeneration1(0x101, 0x0, 0x0, 0x0, 0x1fabb46, 0x12, 0xc420096fc0, 0x24, 0x0, 0x0, ...)
	/tmp/release.ZeQoT/src/github.com/convox/rack/cmd/convox/start.go:181 +0x81f
main.cmdStart(0xc4202ae2c0, 0x0, 0xc4202ae2c0)
	/tmp/release.ZeQoT/src/github.com/convox/rack/cmd/convox/start.go:109 +0x37b
github.com/convox/rack/vendor/gopkg.in/urfave/cli%2ev1.HandleAction(0x1cb8d20, 0x1fdada0, 0xc4202ae2c0, 0xc420060200, 0x0)
	/tmp/release.ZeQoT/src/github.com/convox/rack/vendor/gopkg.in/urfave/cli.v1/app.go:490 +0xd2
github.com/convox/rack/vendor/gopkg.in/urfave/cli%2ev1.Command.Run(0x1f9c051, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1fad27d, 0x13, 0x0, ...)
	/tmp/release.ZeQoT/src/github.com/convox/rack/vendor/gopkg.in/urfave/cli.v1/command.go:210 +0xa95
github.com/convox/rack/vendor/gopkg.in/urfave/cli%2ev1.(*App).Run(0xc42025a340, 0xc42008c040, 0x2, 0x2, 0x0, 0x0)
	/tmp/release.ZeQoT/src/github.com/convox/rack/vendor/gopkg.in/urfave/cli.v1/app.go:255 +0x6f8
main.main()
	/tmp/release.ZeQoT/src/github.com/convox/rack/cmd/convox/main.go:72 +0x17b
```

### `docker-compose.yml`:

```
version: '2'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.app
    cpu_shares: 512
    mem_limit: 1024MB
    environment:
      - PORT=4001
      - RAILS_SERVE_STATIC_FILES=enabled
      - RAILS_LOG_TO_STDOUT=enabled
      - LANG=en_US.UTF-8
    labels:
      - convox.port.443.protocol=tls
      - convox.port.443.proxy=true
    ports:
      - 80:4001/tcp
      - 443:4001/tcp
    privileged: true
```

### `Dockerfile`:

```
FROM my_app/base:latest

ENV PORT 4001
ENV RAILS_ENV production
ENV RAILS_SERVE_STATIC_FILES true
ENV RAILS_LOG_TO_STDOUT true

RUN mkdir -p /usr/src/my_app
WORKDIR /usr/src/my_app

ADD Gemfile /usr/src/my_app/Gemfile
ADD Gemfile.lock /usr/src/my_app/Gemfile.lock
RUN bundle config --global frozen 1 \
    && bundle install --without development:test -j4 \
        --path vendor/bundle \
        --binstubs vendor/bundle/bin \
        --deployment

ADD package.json /usr/src/my_app/package.json
ADD yarn.lock /usr/src/my_app/yarn.lock
RUN mkdir -p /usr/src/my_app/client
ADD client/package.json /usr/src/my_app/client/package.json
ADD client/yarn.lock /usr/src/my_app/client/yarn.lock
RUN yarn install

ADD . /usr/src/my_app

RUN bundle exec rake DATABASE_URL=postgresql:does_not_exist assets:precompile

EXPOSE 4001
CMD ["foreman", "start", "-c", "web=1,worker=2"]
```

Please let me know if you need any more information!
