### ISSUE TITLE
[Gen2] None of my scheduled timers are running

### ISSUE THREAD

**Issue by ndbroadbent** [convox/rack#2550]
Here is my `convox.yml`:

```
timers:
  taskOne:
    schedule: 0 10 * * ?
    command: bundle exec rake task:one
    service: web
  taskTwo:
    schedule: 0 18 * * ?
    command: bundle exec rake task:two
    service: web
```

I'm seeing these errors in the Lambda Management Console, when I click "CloudWatch Events":

<img width="1331" alt="screen shot 2018-03-14 at 1 16 43 am" src="https://user-images.githubusercontent.com/139536/37361615-ed9060f4-2725-11e8-86b0-cce70529a4c8.png">

I'm also not sure how to check the logs to see if the tasks are running. My workaround was to send a Slack notification at the end of each task, and I haven't seen any notifications for 24 hours.
