### ISSUE TITLE
Using underscore in service name causes ELB listener rule creation to fail

### ISSUE THREAD

**Issue by mnylen** [convox/rack#2598]
It seems if a service name in `services` section contains an underscore, creation of the `BalancerServiceNameListenerRule80` resource fails with the following message:

```
2018-04-13T05:29:14Z system/aws/cfm CREATE_FAILED BalancerAdProcessorListenerRule80 Condition value for field 'host-header' must be a valid hostname
```

convox.yml:

```
services:
  ad_processor:
    build: .
    environment:
     ...
    health: /v1/health
    port: 8080
    scale:
      count: 2
      memory: 2048
      cpu: 2048
```

The template that creates the resource: https://github.com/convox/rack/blob/7c971d614ed967464f7fe94109f1eb37243205ce/provider/aws/formation/app.json.tmpl#L120

Maybe this could be checked for in a validation step beforehand?
