### ISSUE TITLE
Add args in build of convox.yml

### ISSUE THREAD

**Issue by kevinhuang12345678** [convox/rack#2635]
Can we add args in build section of convox.yml?

convox.yml:
```
services:
  gen2-arg-test:
    build:
      path: .
      manifest: ./Dockerfile.base
      args:
        - base_arg="new ones"
```
the args (base_arg) is being ignored as of now.

Dockerfile.base:
```
FROM bash:4.4

ARG base_arg="Base arg"

ENV base_env=${base_arg}

CMD echo "got base_env=${base_env}"
```

the output:
```
... got base_env=Base arg
```
expected to be base_env=new ones
