### ISSUE TITLE
support ONBUILD in Dockerfile

### ISSUE THREAD

**Issue by kevinhuang12345678** [convox/rack#2641]
Can we add the support in Dockerfile?

convox.xml
```
services:
  gen2-arg-test:
    build:
      path: .
      manifest: ./Dockerfile.base
#      args:
#        - base_arg="new ones from convox"
    command: cat ./havenlife_test.txt; tail -f /dev/null
```

Dockerfile.mine:
```
FROM kevinhuang12345678/havenlife_test:1.0.0
```

here, Dockerfile.base used to build ```kevinhuang12345678/havenlife_test:1.0.0``` is:
```
FROM bash:4.4

ONBUILD ARG base_arg=""
ONBUILD RUN echo "got base_arg=$base_arg" > ./havenlife_test.txt

CMD ["cat", "./havenlife_test.txt"]
```

after set env value, build and deploy, In the resulting container, the file ```havenlife_test.txt``` should have:
```
got base_arg=new ones from convox
```
but
```
got base_arg=
```
