### ISSUE TITLE
Cron job logs are lost when 6-term schedule syntax is used

### ISSUE THREAD

**Issue by xanderflood** [convox/rack#2656]
When I define a cronjob with 6-term cron syntax, `convox logs` will show that it executes, but it won't print any of the stdout from the cron process. When I use 5-term syntax, everything works perfectly.

Possibly related: when I use 6-term syntax, after each invocation of the job I get a logline of the form:
`2018-05-09T19:05:26Z service/scan:RBZXJKNIIUJ/fa546d69fe31 sh: bin: not found`

I'm not sure what's causing it, but since it doesn't occur with 5-term syntax, I think it might be a failed attempt at logging the cron job's output.

**Comment by ddollar** [comment]
Please include an example from your `convox.yml` here

**Comment by xanderflood** [comment]
Here's the relevant snippet. I'm woefully unfamiliar with convox, but the config file is named `docker-compose.convox.yml`, which I think makes this a Generation 1 application.

This will work and log "it's working" once per minute

```
---
version: '2'
services:
  scan:
    build: ./build/scan
    mem_limit: 16MB
    labels:
      - convox.cron.scan=* * * * ? echo "it's working"
```

But if I change the last line to
`      - convox.cron.scan=* * * * * ? echo "it's working"`
it'll log 
```
2018-05-10T13:01:27Z skew=6485ms command=echo &#34;it&#39;s working&#34; result=success task=[...]
```
like it normally does, but it won't log the echo'd string.
