### ISSUE TITLE
Path level matching

### ISSUE THREAD

**Issue by phuongnd08** [convox/rack#2679]
Please add path level matching for convox.
I can suggest something like this:

```
services:
   web:
     domain:
        - domain1.com
        - domain2.com
     path:
        - /api/*
        - /custom/*

```

The domain and the path should form an AND condition:
So request domain must match at least 1 domain and at least 1 path to be routed to web service.
If one need to have more sophisticated matching he can use multiple services to mutate the routing rules.

If a rules doesn't have a path, it should be placed at the bottom of the routing table (lower priority)
That way make it possible for any unmatched url to routed to a service
