### ISSUE TITLE
Shared environment not available on first deploy?

### ISSUE THREAD

**Issue by chids** [convox/rack#2773]
Release [20180523 ](https://github.com/convox/rack/pull/2692) added support for a [shared environment section to `convos.yml`](https://github.com/convox/rack/pull/2691).

If one tries to use this to set the domain for a service, as per the below example, it will fail to deploy as the `DOMAIN` variable isn't available/used/interpolated and the domain name thus becomes invalid.

<details>
 <summary>Error from ACM as logged by Cloudformation</summary>
<blockquote>
2018-07-19T11:26:26Z system/aws/cfm CREATE_FAILED BalancerBarCertificate 4 validation errors detected: Value '[bar.]' at 'subjectAlternativeNames' failed to satisfy constraint: Member must satisfy constraint: [Member must have length less than or equal to 253, Member must have length greater than or equal to 1, Member must satisfy regular expression pattern: ^(\*\.)?(((?!-)[A-Za-z0-9-]{0,62}[A-Za-z0-9])\.)+((?!-)[A-Za-z0-9-]{1,62}[A-Za-z0-9])$]; Value 'bar.' at 'domainName' failed to satisfy constraint: Member must satisfy regular expression pattern: ^(\*\.)?(((?!-)[A-Za-z0-9-]{0,62}[A-Za-z0-9])\.)+((?!-)[A-Za-z0-9-]{1,62}[A-Za-z0-9])$; Value 'bar.' at 'domainValidationOptions.1.member.validationDomain' failed to satisfy constraint: Member must satisfy regular expression pattern: ^(\*\.)?(((?!-)[A-Za-z0-9-]{0,62}[A-Za-z0-9])\.)+((?!-)[A-Za-z0-9-]{1,62}[A-Za-z0-9])$; Value 'bar.' at 'domainValidationOptions.1.member.domainName' failed to satisfy constraint: Member must satisfy regular expression pattern: ^(\*\.)?(((?!-)[A-Za-z0-9-]{0,62}[A-Za-z0-9])\.)+((?!-)[A-Za-z0-9-]{1,62}[A-Za
</blockquote>
</details>

----

The manifest for the first deploy, which fails:
```yml
environment:
  - DOMAIN=some.domain.com
services:
  web:
    build: .
    command: java -jar service.jar
    domain: web.${DOMAIN}
    health: /health
    port: http:8080
    scale:
      count: 1
      cpu: 256
      memory: 512
```

**Comment by ddollar** [comment]
Shared environment is not currently available for manifest interpolation, only vars set with `convox env` are currently used for substitution inside the manifest.

Is the main use here to have a default?

**Comment by chids** [comment]
The use case is for multi-service applications á la...

```yaml
environment:
  - DOMAIN=some.domain.com
services:
  foo:
    build: .
    command: java -jar service.jar
    domain: foo.${DOMAIN}
    health: /health
    port: http:8080
    scale:
      count: 1
      cpu: 256
      memory: 512
  bar:
    build: .
    command: java -jar service.jar
    domain: bar.${DOMAIN}
    health: /health
    port: http:8080
    scale:
      count: 1
      cpu: 256
      memory: 512
  baz:
    build: .
    command: java -jar service.jar
    domain: baz.${DOMAIN}
    health: /health
    port: http:8080
    scale:
      count: 1
      cpu: 256
      memory: 512
```

...where our current maximum is an application with 15 services on the same base domain.
