### ISSUE TITLE
Request: Support multiple ports on gen 2 apps (maybe via ELB)

### ISSUE THREAD

**Issue by ndbroadbent** [convox/rack#2804]
I would like to run the [GitLab](https://gitlab.com) Omnibus Docker image in my rack. I've got almost everything working, with the exception of SSH access on port 22. For now it's not a deal-breaker, because I can use a "personal access token" to push/pull via https. But it would be nice to support SSH.

I could create a gen 1 app with multiple ports, but I'm worried about how long gen 1 will be supported? Is it officially deprecated and will be removed in future versions?

I was also thinking about how to support this in gen 2. If `convox.yml` contains a `ports` array, maybe it could fall back to setting up an ELB will multiple TCP listeners, instead of using the ALB.

Thanks for your time!

-----------------------------------

In case anyone is trying to set up GitLab in convox, here's the `convox.yml` I'm using:

```
services:
  web:
    image: gitlab/gitlab-ce:latest
    health:
      path: /-/readiness
      grace: 120
    domain: gitlab.mydomain.com
    environment:
      - GITLAB_OMNIBUS_CONFIG
    port: 80
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
    scale:
      memory: 2048
      cpu: 512
      count: 1
```

And the settings in `GITLAB_OMNIBUS_CONFIG`:

```
convox env set GITLAB_OMNIBUS_CONFIG="external_url 'https://gitlab.mydomain.com'; postgresql['enable'] = false; gitlab_rails['db_adapter'] = 'postgresql'; gitlab_rails['db_encoding'] = 'utf8'; gitlab_rails['db_host'] = 'postgres-1234.*********.us-west-2.rds.amazonaws.com'; gitlab_rails['db_port'] = 5432; gitlab_rails['db_username'] = 'postgres'; gitlab_rails['db_password'] = '***************'; letsencrypt['enable'] = false; nginx['listen_port'] = 80; nginx['listen_https'] = false; gitlab_rails['monitoring_whitelist'] = ['127.0.0.0/8', '10.0.0.0/16']"
```
(It would be nice if there was an easier way to set multiline env vars)
