### ISSUE TITLE
timer process doesn't use the link from its service

### ISSUE THREAD

**Issue by frsechet** [convox/rack#2835]
The below convox.yml will define a MAIN_URL environment variable for the `cronjobs` service, however when the cronjob is run from a timer, the MAIN_URL is undefined when the `task` timer is run.  
The variable does not appear in the task definition of the timer service.
```
services:
  cronjobs:
    build: ./something
    links:
      - main

  main:
    build: ./something-else
    port: 3000

timers:
  task:
    schedule: 30 6 * * ?
    command: npm run task
    service: cronjobs
```
