### ISSUE TITLE
Feature request: Allow services to expose only HTTP or HTTPS

### ISSUE THREAD

**Issue by chids** [convox/rack#2848]
Allow disabling HTTP or HTTPS on a per service level, something like...

```yaml
services:
  secure-service:
    protocol: https
  unsecure-service:
    protocol: http
```

...and utilise ALB [redirect action](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-listeners.html#redirect-actions) to redirect requests on the _other_ protocol to the one specified, i.e. HTTPS 👉 HTTP or vice versa.
