### ISSUE TITLE
float env vars are ignored

### ISSUE THREAD

**Issue by frsechet** [convox/rack#2887]
The following convox.yml results in `FLOAT_ENV` not passed to the task definition. However `INT_ENV` and `STRING_ENV` are set.

It stopped working after I upgraded to 20180827171554. Reversing back to 20180824133029 fixed it.

```
services:
  task:
    image: whatever
    environment:
      - STRING_ENV=something
      - INT_ENV=42
      - FLOAT_ENV=0.05
```
