### ISSUE TITLE
Resource does not exist for stack

### ISSUE THREAD

**Issue by DanBrooker** [convox/rack#3104]
I've just updated my rack to 20190126182547 and my postgres and redis resources are no longer showing under `convox resources`, and I'm getting an error when try to proxy a resource.

```
➜ convox resources proxy postgres-1930 -p 5433
ERROR: ValidationError: Resource ResourcePostgres1930 does not exist for stack production-app
	status code: 400, request id: 39aadee1-2400-11e9-aecc-05efaf791228
```

This was working recently and the resource still exist.

How do I attach these resources to the rack/app? I think they were created for a Gen1 app, this app is Gen2 and connects use DATABASE_PATH env vars.

If I add this to my convox.yml, is it going to find the existing database/cache or create new ones?

```yaml
resources:
  postgres:
    type: postgres
    options:
      storage: 100
  redis:
    type: redis
services:
  web:
    resources:
      - postgres
      - redis
```
