### ISSUE TITLE
one-off processes should inherit the full environment

### ISSUE THREAD

**Issue by bobzoller** [convox/rack#336]
given an app with a docker-compose.yml:
```
foo:
  image: alpine
  command: watch env
  environment:
    - SECRET=bar
```

do this:
```
convox deploy
[... snip ...]
convox logs
[ expected: includes SECRET ]
convox run foo env
[ unexpected: does not include SECRET ]
```

the one-off environment also does not include (useful) platform managed variables like `RELEASE` or `PROCESS` either.
