### ISSUE TITLE
Support mem_limit in docker-compose.yml

### ISSUE THREAD

**Issue by anthonyrisinger** [convox/rack#353]
```yaml
main:
  mem_limit: 1024m
  build: .
  ports:
    - 2000:2000
```

Something like that should be the same as a `convox deploy` followed by `convox scale main --memory=1024`
