### ISSUE TITLE
docker-compose.yml environment encoding issue

### ISSUE THREAD

**Issue by bobzoller** [convox/rack#362]
with a docker-compose.yml like this:
```
main:
  image: "alpine:latest"
  command: watch env
  
  environment:
    - ONE=foo&foo
    - "TWO=foo&foo"
```

I see HTML encoded environment variables in the running app:

```
[...snip...]
ONE=foo&amp;foo
TWO=foo&amp;foo
```

despite it _looking_ correct in the ECS Task Definition in the AWS Console...

rack version 20160213224638
