### ISSUE TITLE
Local dev host port conflict using internal load balancers

### ISSUE THREAD

**Issue by mattmanning** [convox/rack#573]
I have a `docker-compose.yml` like this:

```yaml
web:
  links:
    - db1
    - db2
db1:
  ports:
    - 3306
db2:
  ports:
    - 3306
```

The DB image I'm using wants to listen on port 3306 (MySQL). This configuration should be fine in production because each will get its own load balancer. However, locally with `convox start` both containers are started with `3306:3306` as the port mapping, causing a conflict on host port 3306.

Since I'm using linking I don't really care what the host port is. I think this problem could be solved by choosing a random port for it in both cases.
