### ISSUE TITLE
Add support for `volumes_from` in docker-compose.yml

### ISSUE THREAD

**Issue by snario** [convox/rack#614]
As far as I can tell, `volumes_from` is ignored right now. Example:

``` yml
web:
    image: some-djangoapp
    volumes:
        - /app/static
proxy:
    image: my-nginx
    volumes_from:
        - web
```

Where the `proxy` container proxies access to some static folders directory that is defined within the app container.
