### ISSUE TITLE
Hostnames of linked containers are inconsistent when using `convox start` and `docker-compose up`

### ISSUE THREAD

**Issue by snario** [convox/rack#624]
Inside directory `myproject` a `docker-compose.yml`
```
nginx:
    links:
        - web
    ports:
        - 80:80
        - 443:443
web:
     ports:
        - 5000
```
If I reference `web` in `nginx.conf` it fails, but `myproject-web` works. This is because the command `convox start` uses is
```
docker run -i \
    --name myproject-nginx \
    -e WEB_HOST=myproject-web \
    -e WEB_PASSWORD= \
    -e WEB_PATH= \
    -e WEB_PORT=5000 \
    -e WEB_SCHEME=tcp \
    -e WEB_URL=tcp://myproject-web:5000 \
    -e WEB_USERNAME= \
    -p 80:80 \
    -p 443:443 \
    --add-host=myproject-web:172.17.0.3 \
    myproject/nginx

```

This is inconsistent with expected behaviour of `docker-compose`, where the hostname would be simply `web` and not `myproject-web`.
