### ISSUE TITLE
Persistent data stores?

### ISSUE THREAD

**Issue by contra** [convox/rack#694]
( Maybe related to #693 )

Is there any documentation on setting up persistent data stores?

Example configuration, using redis as a session store:

```yaml
web:
  build: .
  command: node /usr/src/app/bin/server
  environment:
    - NODE_ENV=production
    - PORT=3000
    - REDIS_URL
  ports:
    - 80:3000
  links:
    - redis
  volumes:
    - .:/usr/src/app

redis:
  image: convox/redis
  ports:
    - 6379
```

Problem: On every deploy, spins up a new redis container and loses all session information.

Am I doing something wrong here?
