### ISSUE TITLE
web process attempting to connect to mysql too quickly

### ISSUE THREAD

**Issue by mwarkentin** [convox/rack#700]
So, I'm trying to set up a django/mysql application:

* I've created an image similar to `convox/postgres` for mysql here: https://github.com/convox/mysql/pull/1
* I've set up the following `docker-compose.yml`:

```yaml
web:
  build: .
  command: python pronetwork/manage.py runserver
  environment:
    - DATABASE_URL=mysqlgis://mysql:password@pronetwork-mysql:3306/app
  ports:
    - 80:8000
  volumes:
    - .:/app
  links:
    - mysql
mysql:
  image: convox/mysql
  ports:
    - 3306

```
* When I run `convox start`, both `web` and `mysql` containers seem to start around the same time, even though the `web` process should `depend_on` `mysql` based on the `links` configuration
* Here are the output logs (look for `web    | django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'pronetwork-mysql' (111)")`): https://gist.github.com/mwarkentin/98cbf29bd389291b0952d30d08c04a0c
* I'm not sure if this is because of how the entrypoint script is running, or when `docker-compose` considers a dependency "up"
* We can do the following, but this seems really hacky: `command: sleep 15s && python pronetwork/manage.py runserver`

### Expectation

The mysql container finishes booting up, and then `web` launches
