### ISSUE TITLE
Using a range of ports

### ISSUE THREAD

**Issue by rjocoleman** [convox/rack#701]
Docker Compose's file format supports [port ranges](https://docs.docker.com/compose/compose-file/#ports):

e.g.

```
ftp:
  build: .
  ports:
    - "21:2021"
    - "2021:2021"
    - "42000-45000:42000-45000"
  restart: always
```

This should mostly work, I think, but for one issue:

`Promoting RYBULWKGCYG... ERROR: Template format error: Parameter name FtpPort42000-45000Balancer is non alphanumeric.`
