### ISSUE TITLE
convox.port.XXX.protocol doesn't take port-shifting into account

### ISSUE THREAD

**Issue by mwarkentin** [convox/rack#746]
I was playing around with shifting ports - I’m not quite seeing the behaviour I expected. I don’t think the proxy container is taking the port shift I defined into account. Here’s my goal for this app:

* on-rack: exposed on port 443
* local: exposed via https proxy on port 10005

My first attempt:

```
web:
  build: .
  command: /app/bin/web
  labels:
    - convox.port.443.protocol=https
    - convox.start.shift=9562
  ports:
    - 443:80
```

Result: No HTTPS proxy configured. 

```
$ docker ps
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS                             NAMES
05f519354c64        pronetwork/web        "sh -c /app/bin/web"     51 seconds ago      Up 18 seconds       8000/tcp, 0.0.0.0:10005->80/tcp   pronetwork-web
3fa3e1c4fe5b        pronetwork/database   "/docker-entrypoint.s"   52 seconds ago      Up 19 seconds       0.0.0.0:3306->3306/tcp            pronetwork-database
```

Second attempt:

```
web:
  build: .
  command: /app/bin/web
  labels:
    - convox.port.10005.protocol=https
    - convox.start.shift=9562
  ports:
    - 443:80
```

Result: HTTPS proxy configured, but lose the protocol definition if I deployed to a rack

```
$ docker ps
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS              PORTS                             NAMES
f2b1bf962545        convox/proxy          "proxy-link 10005 80 "   40 seconds ago      Up 6 seconds        0.0.0.0:10005->10005/tcp          stupefied_leavitt6
6505f2662f96        pronetwork/web        "sh -c /app/bin/web"     41 seconds ago      Up 7 seconds        8000/tcp, 0.0.0.0:42246->80/tcp   pronetwork-web
d1c9b62024e0        pronetwork/database   "/docker-entrypoint.s"   42 seconds ago      Up 8 seconds        0.0.0.0:3306->3306/tcp            pronetwork-database
```

**Comment by mwarkentin** [comment]
It also appears that only the first process defined with an https label gets a proxy container created:

```
$ docker ps
CONTAINER ID        IMAGE                 COMMAND                  CREATED              STATUS              PORTS                      NAMES
8966aaf152d3        convox/proxy          "proxy-link 10005 80 "   About a minute ago   Up 22 seconds       0.0.0.0:10005->10005/tcp   awesome_einstein
7bff45700fb5        pronetwork/web        "sh -c /app/bin/web"     About a minute ago   Up 24 seconds       0.0.0.0:40751->80/tcp      pronetwork-web
79b39d2ae4ff        pronetwork/rpc        "sh -c /app/bin/rpc"     About a minute ago   Up 25 seconds       0.0.0.0:2005->80/tcp       pronetwork-rpc
c98a12e5880b        pronetwork/database   "/docker-entrypoint.s"   About a minute ago   Up 26 seconds       0.0.0.0:3306->3306/tcp     pronetwork-database
```

docker-compose.yml:

```yaml
web:
  build: .
  command: /app/bin/web
  labels:
    - convox.port.443.protocol=https
    - convox.port.10005.protocol=https  # Temporary workaround for https://github.com/convox/rack/issues/746
    - convox.start.shift=9562
  ports:
    - 443:80
  links:
    - database
rpc:
  build: .
  command: /app/bin/rpc
  labels:
    -convox.port.2005.protocol=https
  ports:
    - 2005:80
  links:
    - database
database:
  image: convox/mysql
  ports:
    - 3306
  volumes:
    - ../../data-volumes/pronetwork/mysql:/var/lib/mysql
```
