### ISSUE TITLE
File ownership switching to root

### ISSUE THREAD

**Issue by crearc** [convox/rack#784]
I'm having an issue when running `convox start`. When I edit a file it switches the owner of the file from my unix user to root. I believe it happens during the syncing process, but never returns the ownership to my user (and my text editor then can't save the file any more).

```
docker -v
> Docker version 1.11.1, build 5604cbe

convox -v
> client: 20160617202022
> server: 20160615213630 (console.convox.com)
```

**Comment by ddollar** [comment]
When you save the file locally the local uid changes to root? Do you have any volume mounts in your docker-compose.yml ?

**Comment by crearc** [comment]
From `ls -la` with `emails.py`. Changes owner and group:
![screenshot from 2016-06-20 10 45 58](https://cloud.githubusercontent.com/assets/395144/16200770/46690f12-36d4-11e6-98d0-472a40f126b6.png)

Yes I have a volume mount for the app folder. 

`docker-compose.yml`:
```
worker:
  build: .
  command: python manage.py rqworker
  environment:
    - ANALYSIS_DB_HOST
    - ANALYSIS_DB_PASSWORD
    - ANALYSIS_DB_USER
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - DJANGO_SETTINGS_MODULE=das.settings.convox
  volumes:
    - .:/usr/src/app
  links:
    - redis

scheduler:
  build: .
  command: python manage.py scheduler
  environment:
    - ANALYSIS_DB_HOST
    - ANALYSIS_DB_PASSWORD
    - ANALYSIS_DB_USER
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - DJANGO_SETTINGS_MODULE=das.settings.convox
  volumes:
    - .:/usr/src/app
  links:
    - redis

notebook:
  build: .
  command: python manage.py shell_plus --notebook
  environment:
    - ANALYSIS_DB_HOST
    - ANALYSIS_DB_USER
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - DJANGO_SETTINGS_MODULE=das.settings.convox
  volumes:
    - .:/usr/src/app
  links:
    - redis

web:
  build: .
  command: gunicorn --workers=3 das.wsgi --bind 0.0.0.0:8000 --log-file -
  environment:
    - ANALYSIS_DB_HOST
    - ANALYSIS_DB_PASSWORD
    - ANALYSIS_DB_USER
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - DJANGO_SETTINGS_MODULE=das.settings.convox
  ports:
    - 8000:8000
  volumes:
    - .:/usr/src/app
  links:
    - redis

redis:
  image: convox/redis
  ports:
    - 6379

```
