### ISSUE TITLE
Code sync with relative Dockerfile doesn't work

### ISSUE THREAD

**Issue by ddollar** [convox/rack#814]
Project structure:

```
backend/
  backend.php
frontend/
  frontend.php
```

docker-compose.yml:

```
backend:
  build: ./backend
frontend:
  build: ./frontend
```

Code sync seems to start at the root of the repo locally instead of the same root that will be present in the container (`backend/` or `frontend/`). This causes files to be created like `./backend/backend/backend.php`.
