### ISSUE TITLE
Too many process types causes a CloudFormation Parameter Limit Error

### ISSUE THREAD

**Issue by nzoschke** [convox/rack#816]
If you have a docker-compose file with:

* More than 16 process types with no port mappings
* More than 5 process types with 1 port mapping

You can hit a CloudFormation error on deploy

```yaml
web: &web
  build: .
  command: bin/web
  ports:
    - 80:80
    - 443:80
worker: &worker
  <<: *web
  command: bundle exec rake jobs:work
  ports: []
w2:
  <<: *worker
  command: bundle exec rake jobs:w2
w3:
  <<: *worker
  command: bundle exec rake jobs:w3
w4:
  <<: *worker
  command: bundle exec rake jobs:w4
w5:
  <<: *worker
  command: bundle exec rake jobs:w5
w6:
  <<: *worker
  command: bundle exec rake jobs:w6
w7:
  <<: *worker
  command: bundle exec rake jobs:w7
w8:
  <<: *worker
  command: bundle exec rake jobs:w8
w9:
  <<: *worker
  command: bundle exec rake jobs:w9
w10:
  <<: *worker
  command: bundle exec rake jobs:w10
w11:
  <<: *worker
  command: bundle exec rake jobs:w11
```

```bash
$ convox deploy
...
Promoting RTMUEOBWWZA... ERROR: Template format error: Parameter count 61 is greater than max allowed 60`
```
