### ISSUE TITLE
Improved persistent volumes for development

### ISSUE THREAD

**Issue by ianmalott** [convox/rack#850]
**Goal:** when developing an application locally with a database process declared in its docker-compose.yml, the database would ideally persist across container runs, i.e. from one `convox start` to the next, with as little configuration as possible.

**Current state:** you can achieve persistence across runs, but need to specify a `/host/path:/container/path` volume mapping like the following in docker-compose.yml:

```
database:
  image: convox/postgres
  ports:
    - 5432
  volumes:
    - /Users/foo/docker-volumes/example_app/postgresql/data:/var/lib/postgresql/data
```

This potentially leaves the user to deal with...

1. Picking a sensible host path that can be reused across a team's dev machines
1. Whitelisting a chosen path with Docker (e.g. Docker for Mac > Preferences > File Sharing)
1. Namespacing paths per project, app, container, etc.

**Possible paths forward**

1. Using a 2-part `/host/past:/container/path` declaration, but establishing a convox-specific convention so users don't have to take time coming up with their own
1. Figuring out if there's a way to get the 1-part declaration to result in the desired persistence
