### ISSUE TITLE
Files syncing to unexpected  dir in container

### ISSUE THREAD

**Issue by ianmalott** [convox/rack#897]
When running `convox start`, files created in `backend/` get synced to the container at `/'/usr/src/app'/backend` instead of `/usr/src/app/backend`.

---

Project structure
```
.
├── backend
│   ├── Dockerfile
│   ├── foo
│   ├── package.json
│   └── server.js
├── docker-compose.yml
└── frontend
    ├── Dockerfile
    ├── package.json
    └── server.js
```

docker-compose.yml
```
version: '2'
services:
  backend:
    build: ./backend
    ports:
      - 8001:8000

  frontend:
    build: ./frontend
    ports:
      - 80:8000
```

Dockerfile for both backend/ and frontend/
```
FROM nodesource/node:6.2

ADD package.json package.json
RUN npm install --loglevel error
ADD . .

EXPOSE 8000

CMD ["npm", "start"]
```
