### ISSUE TITLE
v2 networks flag not being sent to underlying docker run

### ISSUE THREAD

**Issue by cleblanc87** [convox/rack#901]
On `convox start`, given the following compose: 

```
version: "2"
services:
  memcached:
    image: memcached
    ports:
      - 11211:11211
networks:
  dev:
    external:
      name: "arthrex_dev"
```

Actual docker run command:
`docker run -i --name arthrex.com-memcached -p 11211:11211 arthrex.com/memcached`

Expected docker run command (previous behavior):
`docker run -i --name arthrex.com-memcached -p 11211:11211 --net arthrex_dev arthrex.com/memcached`

the arthrex_dev network has been created in an external docker-compose

```
version: '2'
networks:
  dev:
    driver: bridge
```

via `docker-compose --project-name arthrex up -d`
